query GetAgentTaskById($id: UUID!) {
    agentTaskById(id: $id) {
        id
        title
        status
        deliverableId
        result
        errors
        commitHash
        complexityRating
        dependsOnDevTask
        promptTokens
        completionTokens
        executionDurationInSeconds
        model
    }
}

query GetAgentTasks($projectId: UUID, $status: [AgentTaskStatus!]) {
    agentTasks(itemId: $projectId) {
        id
        title
        status
        deliverableId
        result
        errors
        commitHash
        complexityRating
        dependsOnDevTask
        promptTokens
        completionTokens
        executionDurationInSeconds
        model
    }
}
