query GetAgentTask($id: UUID!) {
    agentTask(id: $id) {
        id
        projectId
        deliverableId
        title
        status
        description
        result
        errors
        commitHash
        complexityRating
        dependsOnAgentTaskId
        promptTokens
        completionTokens
        executionDurationInSeconds
        agent
        deliverable {
            id
            title
        }
        project {
            id
            name
            repository
        }
    }
}

query GetAgentTasks($deliverableId: UUID!) {
    agentTasks(where: { deliverableId: { eq: $deliverableId } }, first: 100) {
        nodes {
            id
            projectId
            deliverableId
            title
            status
            description
            result
            errors
            commitHash
            complexityRating
            dependsOnAgentTaskId
            promptTokens
            completionTokens
            executionDurationInSeconds
            agent
            deliverable {
                id
                title
            }
            project {
                id
                name
            }
        }
    }
}
