query GetAgentTaskById($id: UUID!) {
    agentTaskById(id: $id) {
        id
        title
        status
        deliverableId
        description
        result
        errors
        commitHash
        complexityRating
        dependsOnAgentTaskId
        promptTokens
        completionTokens
        executionDurationInSeconds
        agent
    }
}

query GetAgentTasks($projectId: UUID) {
    agentTasks(itemId: $projectId) {
        id
        title
        status
        deliverableId
        description
        result
        errors
        commitHash
        complexityRating
        dependsOnAgentTaskId
        promptTokens
        completionTokens
        executionDurationInSeconds
        agent
    }
}
