query GetDefects {
    defects {
        nodes {
            id
            title
            description
            status
            severity
            projectId
            parentFeatureId
            createdAt
            updatedAt
        }
    }
}

query GetDefectById($id: UUID!) {
    defectById(id: $id) {
        id
        title
        description
        acceptanceCriteria
        plan
        result
        errors
        securityImpact
        performanceImpact
        testPlan
        deploymentPlan
        openQuestions
        status
        severity
        projectId
        parentFeatureId
        createdAt
        updatedAt
    }
}
