query GetDeliverables {
    deliverables {
        id
        title
        description
        status
        type
        acceptanceCriteria
        plan
        securityImpact
        performanceImpact
        testPlan
        deploymentPlan
        openQuestions
        result
    }
}

query GetDeliverableById($id: UUID!) {
    deliverableById(id: $id) {
        id
        title
        description
        status
        type
        acceptanceCriteria
        plan
        securityImpact
        performanceImpact
        testPlan
        deploymentPlan
        openQuestions
        result
    }
}
