query GetTaskById($id: ID!) {
    taskById(id: $id) {
        id
        title
        deliverable
        acceptanceCriteria
        risks
        requiredFollowUps
        complexity
        status
        feature {
            id
            title
        }
        createdAt
        updatedAt
    }
}

query GetTasks {
    tasks {
        nodes {
            id
            title
            deliverable
            acceptanceCriteria
            risks
            requiredFollowUps
            complexity
            status
            feature {
                id
                title
            }
            createdAt
            updatedAt
        }
    }
}
