query GetTaskById($id: UUID!) {
    taskById(id: $id) {
        id
        title
        deliverable
        acceptanceCriteria
        risks
        requiredFollowUps
        complexityRating
        result
        status
        featureId
        createdAt
        updatedAt
    }
}

query GetTasks($featureId: UUID, $status: [TaskStatus!]) {
    tasks(featureId: $featureId, status: $status) {
        nodes {
            id
            title
            deliverable
            acceptanceCriteria
            risks
            requiredFollowUps
            complexityRating
            result
            status
            featureId
            createdAt
            updatedAt
        }
    }
}
