// Generated by `npm run codegen`. Do not edit manually.
// Source: codegen.ts (uses @graphql-codegen/client-preset).
//
// This file contains the typed document constants (TypedDocumentNode<Query, Variables>)
// for each operation in src/graphql/queries.graphql. Pass these to client.request(...)
// and the response + variables types are inferred automatically.

import { gql } from 'graphql-tag';
import type { TypedDocumentNode } from '@graphql-typed-document-node/core';
import type { DeliverableStatus, DeliverableType, Exact } from './graphql.js';

// --- Operation result types (typed-document-node references these) ---
export type GetProjectsQueryVariables = Exact<{
  first?: number | null | undefined;
}>;


export type GetProjectsQuery = { projects: { nodes: Array<{ id: string, name: string, description: string, repository: string }> | null } | null };

export type GetProjectByIdQueryVariables = Exact<{
  id: string;
}>;


export type GetProjectByIdQuery = { project: { id: string, name: string, description: string, repository: string, deliverables: Array<{ id: string, title: string, type: DeliverableType, status: DeliverableStatus, description: string | null }> } | null };

export type GetProjectsForResolverQueryVariables = Exact<{ [key: string]: never; }>;


export type GetProjectsForResolverQuery = { projects: { nodes: Array<{ id: string, name: string, description: string, repository: string, deliverables: Array<{ id: string, title: string, type: DeliverableType, status: DeliverableStatus, description: string | null }> }> | null } | null };

export type GetPlanDeliverablesForProjectQueryVariables = Exact<{
  projectId: string;
}>;


export type GetPlanDeliverablesForProjectQuery = { deliverables: { nodes: Array<{ id: string, title: string, type: DeliverableType, status: DeliverableStatus, description: string | null }> | null } | null };

// --- Typed document constants ---
export const GetProjectsDocument: TypedDocumentNode<GetProjectsQuery, GetProjectsQueryVariables> = gql`
    query GetProjects($first: Int) {
  projects(first: $first) {
    nodes {
      id
      name
      description
      repository
    }
  }
}
    `;
export const GetProjectByIdDocument: TypedDocumentNode<GetProjectByIdQuery, GetProjectByIdQueryVariables> = gql`
    query GetProjectById($id: UUID!) {
  project(id: $id) {
    id
    name
    description
    repository
    deliverables {
      id
      title
      type
      status
      description
    }
  }
}
    `;
export const GetProjectsForResolverDocument: TypedDocumentNode<GetProjectsForResolverQuery, GetProjectsForResolverQueryVariables> = gql`
    query GetProjectsForResolver {
  projects {
    nodes {
      id
      name
      description
      repository
      deliverables {
        id
        title
        type
        status
        description
      }
    }
  }
}
    `;
export const GetPlanDeliverablesForProjectDocument: TypedDocumentNode<GetPlanDeliverablesForProjectQuery, GetPlanDeliverablesForProjectQueryVariables> = gql`
    query GetPlanDeliverablesForProject($projectId: UUID!) {
  deliverables(where: {projectId: {eq: $projectId}, status: {eq: PLAN}}) {
    nodes {
      id
      title
      type
      status
      description
    }
  }
}
    `;
