erDiagram

    Project {
        string Name
        string Description
        string Repository
    }

    Deliverable {
        guid ProjerctId
        string Title
        string Status "Draft | Planning | Ready | InProgress | Done | Failed | Rejected | NeedsReview"
        string Type "Feature | Defect | Maintenance"
        string Description
        string AcceptanceCriteria "optional"
        string AgentFeedback "optional"
        string ExecutionPlan "optional"
        string SecurityImpact "optional"
        string PerformanceImpact "optional"
        string TestPlan "optional"
        string DeploymentPlan "optional"
        string Blocking "optional"
    }

    AgentTask {
        guid ProjerctId
        guid DeliverableId
        string Title
        string Status "Ready | InProgress | Done | Failed | Rejected | NeedsReview"
        string Description
        string Result "optional"
        string Errors "optional"
        string CommitHash "optional"
        int ComplexityRating
        guid DependsOnAgentTaskId "optional"
        int PromptTokens "optional"
        int CompletionTokens "optional"
        int ExecutionDurationInSeconds "optional"
        string Agent "optional"
    }

    LargeLanguageModel {
        string Url
        string Model
        string ModelAlias
        string ApiKey
        int MaxComplexity
        int MaxConcurrency
    }

    %% Relationships
    Project ||--o{ Deliverable : "has many"
    Deliverable ||--o{ AgentTask : "has many"
    